# Generated by Django 5.1.3 on 2024-12-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="3-letter ISO 4217 code", max_length=3, unique=True
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="exchange rate relative to the base currency (USD)",
                        max_digits=255,
                    ),
                ),
            ],
        ),
    ]
